# Main Config
run_scraper_pipeline_params:
  dailyfx_out_feathername: 'dailyfx_{{suffix}}.feather'
  econtimes_out_feathername: 'econtimes_{{suffix}}.feather'
  financialtimes_out_feathername: 'financialtimes_{{suffix}}.feather'

run_prediction_pipeline_params:
  dailyfx_scrape_feathername: 'dailyfx_{{suffix}}.feather'
  econtimes_scrape_feathername: 'econtimes_{{suffix}}.feather'
  financialtimes_scrape_feathername: 'financialtimes_{{suffix}}.feather'
  dailyfx_out_feathername: 'dailyfx_result_{{suffix}}.feather'
  econtimes_out_feathername: 'econtimes_result_{{suffix}}.feather'
  financialtimes_out_feathername: 'financialtimes_result_{{suffix}}.feather'

postprocess_data_params:
  dailyfx_pred_feathername: 'dailyfx_result_{{suffix}}.feather'
  econtimes_pred_feathername: 'econtimes_result_{{suffix}}.feather'
  financialtimes_pred_feathername : 'financialtimes_result_{{suffix}}.feather'
  out_feathername: 'combined_data.feather'
